# English Proficiency Score (0-100)
# Reference: Native=98, Netherlands/Scandinavia=85-90, Thailand=55, Vietnam=35, Japan=40
NEW_ENGLISH = {
    'Faro': 55, 'Canggu': 45, 'Koh Samui': 50, 'Da Nang': 32, 'Hoi An': 30,
    'Hua Hin': 40, 'Puerto Vallarta': 45, 'Tulum': 48, 'Mazatlán': 30,
    'Cádiz': 35, 'Taormina': 32, 'Kotor': 55, 'Cascais': 65, 'Las Palmas': 45,
    'Santa Cruz de Tenerife': 42, 'Paphos': 75, 'Limassol': 78, 'Nha Trang': 28,
    'Siargao': 72, 'El Nido': 70, 'Essaouira': 35, 'Punta Cana': 45, 'Zanzibar': 55,
    'Cuenca': 35, 'Da Lat': 25, 'Ubud': 50, 'Innsbruck': 72, 'Interlaken': 78,
    'San Cristóbal de las Casas': 25, 'Oaxaca': 30, 'Antigua Guatemala': 45,
    'Pokhara': 45, 'Luang Prabang': 25,
    'Colombo': 65, 'Accra': 85, 'Tunis': 40, 'Tangier': 42, 'Amman': 58,
    'Beirut': 68, 'Muscat': 62, 'Batumi': 35, 'Yerevan': 42, 'Vientiane': 22,
    'Yangon': 35, 'Kampala': 75, 'Addis Ababa': 40, 'Dakar': 25, 'Kathmandu': 45,
    'Bratislava': 62, 'Ljubljana': 72, 'Vilnius': 68, 'Plovdiv': 42,
    'Sofia': 48, 'Belgrade': 55, 'Sarajevo': 48, 'Tirana': 45,
    'Funchal': 55, 'Palma de Mallorca': 48,
    'Mérida': 28, 'Quito': 30, 'La Paz': 22, 'Santo Domingo': 35,
    'San Juan': 75,
    'Chiang Rai': 35, 'Ipoh': 55, 'Dumaguete': 72, 'Jeju': 35,
    'Taichung': 42, 'Vung Tau': 25,
}

# Expat Community Size: 'small', 'medium', or 'large'
NEW_EXPAT = {
    'Faro': 'medium', 'Canggu': 'large', 'Koh Samui': 'medium', 'Da Nang': 'large',
    'Hoi An': 'medium', 'Hua Hin': 'medium', 'Puerto Vallarta': 'large',
    'Tulum': 'large', 'Mazatlán': 'medium', 'Cádiz': 'small', 'Taormina': 'small',
    'Kotor': 'small', 'Cascais': 'medium', 'Las Palmas': 'large',
    'Santa Cruz de Tenerife': 'medium', 'Paphos': 'large', 'Limassol': 'large',
    'Nha Trang': 'medium', 'Siargao': 'medium', 'El Nido': 'small',
    'Essaouira': 'small', 'Punta Cana': 'medium', 'Zanzibar': 'small',
    'Cuenca': 'large', 'Da Lat': 'small', 'Ubud': 'large', 'Innsbruck': 'small',
    'Interlaken': 'small', 'San Cristóbal de las Casas': 'medium',
    'Oaxaca': 'large', 'Antigua Guatemala': 'large', 'Pokhara': 'medium',
    'Luang Prabang': 'small',
    'Colombo': 'medium', 'Accra': 'medium', 'Tunis': 'small', 'Tangier': 'medium',
    'Amman': 'medium', 'Beirut': 'medium', 'Muscat': 'medium', 'Batumi': 'medium',
    'Yerevan': 'small', 'Vientiane': 'small', 'Yangon': 'small',
    'Kampala': 'small', 'Addis Ababa': 'small', 'Dakar': 'small', 'Kathmandu': 'medium',
    'Bratislava': 'small', 'Ljubljana': 'small', 'Vilnius': 'small',
    'Plovdiv': 'small', 'Sofia': 'medium', 'Belgrade': 'medium',
    'Sarajevo': 'small', 'Tirana': 'small', 'Funchal': 'medium',
    'Palma de Mallorca': 'large',
    'Mérida': 'medium', 'Quito': 'medium', 'La Paz': 'small',
    'Santo Domingo': 'medium', 'San Juan': 'medium',
    'Chiang Rai': 'small', 'Ipoh': 'small', 'Dumaguete': 'medium',
    'Jeju': 'small', 'Taichung': 'small', 'Vung Tau': 'small',
}

# Culture Score (0-100)
# Reference: Paris=96, Bangkok=70, Bali=60, small beach towns=35-50
NEW_CULTURE = {
    'Faro': 52, 'Canggu': 45, 'Koh Samui': 42, 'Da Nang': 48, 'Hoi An': 65,
    'Hua Hin': 40, 'Puerto Vallarta': 45, 'Tulum': 48, 'Mazatlán': 42,
    'Cádiz': 68, 'Taormina': 72, 'Kotor': 62, 'Cascais': 58, 'Las Palmas': 55,
    'Santa Cruz de Tenerife': 52, 'Paphos': 55, 'Limassol': 50, 'Nha Trang': 38,
    'Siargao': 30, 'El Nido': 28, 'Essaouira': 58, 'Punta Cana': 32, 'Zanzibar': 55,
    'Cuenca': 55, 'Da Lat': 42, 'Ubud': 62, 'Innsbruck': 68, 'Interlaken': 55,
    'San Cristóbal de las Casas': 65, 'Oaxaca': 75, 'Antigua Guatemala': 62,
    'Pokhara': 48, 'Luang Prabang': 68,
    'Colombo': 55, 'Accra': 48, 'Tunis': 60, 'Tangier': 62, 'Amman': 62,
    'Beirut': 72, 'Muscat': 55, 'Batumi': 45, 'Yerevan': 58, 'Vientiane': 45,
    'Yangon': 62, 'Kampala': 40, 'Addis Ababa': 50, 'Dakar': 55, 'Kathmandu': 60,
    'Bratislava': 60, 'Ljubljana': 62, 'Vilnius': 58, 'Plovdiv': 55,
    'Sofia': 58, 'Belgrade': 62, 'Sarajevo': 60, 'Tirana': 48,
    'Funchal': 52, 'Palma de Mallorca': 55,
    'Mérida': 62, 'Quito': 60, 'La Paz': 55, 'Santo Domingo': 52,
    'San Juan': 62,
    'Chiang Rai': 50, 'Ipoh': 42, 'Dumaguete': 35, 'Jeju': 55,
    'Taichung': 52, 'Vung Tau': 35,
}

# City to full country name (for retirement tool display)
NEW_CITY_TO_COUNTRY_FULL = {
    'Faro': 'Portugal', 'Canggu': 'Indonesia', 'Koh Samui': 'Thailand',
    'Da Nang': 'Vietnam', 'Hoi An': 'Vietnam', 'Hua Hin': 'Thailand',
    'Puerto Vallarta': 'Mexico', 'Tulum': 'Mexico', 'Mazatlán': 'Mexico',
    'Cádiz': 'Spain', 'Taormina': 'Italy', 'Kotor': 'Montenegro',
    'Cascais': 'Portugal', 'Las Palmas': 'Spain', 'Santa Cruz de Tenerife': 'Spain',
    'Paphos': 'Cyprus', 'Limassol': 'Cyprus', 'Nha Trang': 'Vietnam',
    'Siargao': 'Philippines', 'El Nido': 'Philippines', 'Essaouira': 'Morocco',
    'Punta Cana': 'Dominican Republic', 'Zanzibar': 'Tanzania',
    'Cuenca': 'Ecuador', 'Da Lat': 'Vietnam', 'Ubud': 'Indonesia',
    'Innsbruck': 'Austria', 'Interlaken': 'Switzerland',
    'San Cristóbal de las Casas': 'Mexico', 'Oaxaca': 'Mexico',
    'Antigua Guatemala': 'Guatemala', 'Pokhara': 'Nepal',
    'Luang Prabang': 'Laos',
    'Colombo': 'Sri Lanka', 'Accra': 'Ghana', 'Tunis': 'Tunisia',
    'Tangier': 'Morocco', 'Amman': 'Jordan', 'Beirut': 'Lebanon',
    'Muscat': 'Oman', 'Batumi': 'Georgia', 'Yerevan': 'Armenia',
    'Vientiane': 'Laos', 'Yangon': 'Myanmar', 'Kampala': 'Uganda',
    'Addis Ababa': 'Ethiopia', 'Dakar': 'Senegal', 'Kathmandu': 'Nepal',
    'Bratislava': 'Slovakia', 'Ljubljana': 'Slovenia', 'Vilnius': 'Lithuania',
    'Plovdiv': 'Bulgaria', 'Sofia': 'Bulgaria', 'Belgrade': 'Serbia',
    'Sarajevo': 'Bosnia and Herzegovina', 'Tirana': 'Albania',
    'Funchal': 'Portugal', 'Palma de Mallorca': 'Spain',
    'Mérida': 'Mexico', 'Quito': 'Ecuador', 'La Paz': 'Bolivia',
    'Santo Domingo': 'Dominican Republic', 'San Juan': 'United States',
    'Chiang Rai': 'Thailand', 'Ipoh': 'Malaysia', 'Dumaguete': 'Philippines',
    'Jeju': 'South Korea', 'Taichung': 'Taiwan', 'Vung Tau': 'Vietnam',
}

# City coordinates [latitude, longitude]
NEW_COORDS = {
    'Faro': [37.0194, -7.9304], 'Canggu': [-8.6478, 115.1385],
    'Koh Samui': [9.5120, 100.0136], 'Da Nang': [16.0544, 108.2022],
    'Hoi An': [15.8801, 108.3380], 'Hua Hin': [12.5684, 99.9577],
    'Puerto Vallarta': [20.6534, -105.2253], 'Tulum': [20.2115, -87.4654],
    'Mazatlán': [23.2494, -106.4111], 'Cádiz': [36.5271, -6.2886],
    'Taormina': [37.8516, 15.2866], 'Kotor': [42.4247, 18.7712],
    'Cascais': [38.6979, -9.4215], 'Las Palmas': [28.1235, -15.4363],
    'Santa Cruz de Tenerife': [28.4636, -16.2518],
    'Paphos': [34.7754, 32.4245], 'Limassol': [34.6786, 33.0413],
    'Nha Trang': [12.2388, 109.1967], 'Siargao': [9.8489, 126.0458],
    'El Nido': [11.1761, 119.3930], 'Essaouira': [31.5085, -9.7595],
    'Punta Cana': [18.5601, -68.3725], 'Zanzibar': [-6.1659, 39.1989],
    'Cuenca': [-2.9001, -79.0059], 'Da Lat': [11.9404, 108.4583],
    'Ubud': [-8.5069, 115.2625], 'Innsbruck': [47.2692, 11.4041],
    'Interlaken': [46.6863, 7.8632],
    'San Cristóbal de las Casas': [16.7370, -92.6376],
    'Oaxaca': [17.0732, -96.7266], 'Antigua Guatemala': [14.5586, -90.7295],
    'Pokhara': [28.2096, 83.9856], 'Luang Prabang': [19.8856, 102.1347],
    'Colombo': [6.9271, 79.8612], 'Accra': [5.6037, -0.1870],
    'Tunis': [36.8065, 10.1815], 'Tangier': [35.7595, -5.8340],
    'Amman': [31.9454, 35.9284], 'Beirut': [33.8938, 35.5018],
    'Muscat': [23.5880, 58.3829], 'Batumi': [41.6168, 41.6367],
    'Yerevan': [40.1792, 44.4991], 'Vientiane': [17.9757, 102.6331],
    'Yangon': [16.8661, 96.1951], 'Kampala': [0.3476, 32.5825],
    'Addis Ababa': [9.0245, 38.7468], 'Dakar': [14.7167, -17.4677],
    'Kathmandu': [27.7172, 85.3240],
    'Bratislava': [48.1486, 17.1077], 'Ljubljana': [46.0569, 14.5058],
    'Vilnius': [54.6872, 25.2797], 'Plovdiv': [42.1354, 24.7453],
    'Sofia': [42.6977, 23.3219], 'Belgrade': [44.7866, 20.4489],
    'Sarajevo': [43.8563, 18.4131], 'Tirana': [41.3275, 19.8187],
    'Funchal': [32.6669, -16.9241], 'Palma de Mallorca': [39.5696, 2.6502],
    'Mérida': [20.9674, -89.5926], 'Quito': [-0.1807, -78.4678],
    'La Paz': [-16.4897, -68.1193], 'Santo Domingo': [18.4861, -69.9312],
    'San Juan': [18.4655, -66.1057],
    'Chiang Rai': [19.9105, 99.8406], 'Ipoh': [4.5975, 101.0901],
    'Dumaguete': [9.3068, 123.3054], 'Jeju': [33.4996, 126.5312],
    'Taichung': [24.1477, 120.6736], 'Vung Tau': [10.3460, 107.0843],
}

# Lifestyle tags for each city
NEW_LIFESTYLE = {
    'Faro': ['smaller_city', 'beach'], 'Canggu': ['smaller_city', 'beach'],
    'Koh Samui': ['smaller_city', 'beach'], 'Da Nang': ['smaller_city', 'beach'],
    'Hoi An': ['smaller_city', 'beach'], 'Hua Hin': ['smaller_city', 'beach'],
    'Puerto Vallarta': ['smaller_city', 'beach'], 'Tulum': ['smaller_city', 'beach'],
    'Mazatlán': ['smaller_city', 'beach'], 'Cádiz': ['smaller_city', 'beach'],
    'Taormina': ['smaller_city', 'beach', 'mountain'],
    'Kotor': ['smaller_city', 'beach', 'mountain'],
    'Cascais': ['smaller_city', 'beach'], 'Las Palmas': ['smaller_city', 'beach'],
    'Santa Cruz de Tenerife': ['smaller_city', 'beach'],
    'Paphos': ['smaller_city', 'beach'], 'Limassol': ['smaller_city', 'beach'],
    'Nha Trang': ['smaller_city', 'beach'], 'Siargao': ['smaller_city', 'beach'],
    'El Nido': ['smaller_city', 'beach'], 'Essaouira': ['smaller_city', 'beach'],
    'Punta Cana': ['smaller_city', 'beach'], 'Zanzibar': ['smaller_city', 'beach'],
    'Cuenca': ['smaller_city', 'mountain'], 'Da Lat': ['smaller_city', 'mountain'],
    'Ubud': ['smaller_city', 'mountain'], 'Innsbruck': ['smaller_city', 'mountain'],
    'Interlaken': ['smaller_city', 'mountain'],
    'San Cristóbal de las Casas': ['smaller_city', 'mountain'],
    'Oaxaca': ['smaller_city', 'mountain'],
    'Antigua Guatemala': ['smaller_city', 'mountain'],
    'Pokhara': ['smaller_city', 'mountain'],
    'Luang Prabang': ['smaller_city', 'mountain'],
    'Colombo': ['major_city', 'beach'], 'Accra': ['major_city'],
    'Tunis': ['major_city'], 'Tangier': ['major_city', 'beach'],
    'Amman': ['major_city', 'mountain'], 'Beirut': ['major_city'],
    'Muscat': ['major_city'], 'Batumi': ['major_city', 'beach'],
    'Yerevan': ['major_city', 'mountain'], 'Vientiane': ['major_city'],
    'Yangon': ['major_city'], 'Kampala': ['major_city'],
    'Addis Ababa': ['major_city', 'mountain'], 'Dakar': ['major_city'],
    'Kathmandu': ['major_city', 'mountain'],
    'Bratislava': ['major_city'], 'Ljubljana': ['smaller_city', 'mountain'],
    'Vilnius': ['major_city'], 'Plovdiv': ['smaller_city'],
    'Sofia': ['major_city', 'mountain'], 'Belgrade': ['major_city'],
    'Sarajevo': ['major_city', 'mountain'], 'Tirana': ['major_city'],
    'Funchal': ['smaller_city', 'beach', 'mountain'],
    'Palma de Mallorca': ['smaller_city', 'beach'],
    'Mérida': ['major_city'], 'Quito': ['major_city', 'mountain'],
    'La Paz': ['major_city', 'mountain'],
    'Santo Domingo': ['major_city', 'beach'],
    'San Juan': ['major_city', 'beach'],
    'Chiang Rai': ['smaller_city', 'mountain'], 'Ipoh': ['smaller_city'],
    'Dumaguete': ['smaller_city', 'beach'],
    'Jeju': ['smaller_city', 'beach', 'mountain'],
    'Taichung': ['major_city'], 'Vung Tau': ['smaller_city', 'beach'],
}
